version: '3.8'

services:
  app:
    build: .
    container_name: crimesnews-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
