name: BuildHostMakePyinstaller

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Tag'
        required: true
        default: ''
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build with pyinstaller
      run: |
        python -m PyInstaller CrimeNews.py
    - uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: CrimesNews.zip
    - uses: actions/upload-artifact@v2
      with:
        name: CrimesNews.zip
        path: CrimesNews.zip
    - name: release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.event.inputs.tagname }}
        release_name: ${{ github.event.inputs.tagename }}
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: CrimesNews.zip
        asset_name: CrimesNews.zip
        asset_content_type: application/zip